spring:
  datasource:
    url: jdbc:mysql://localhost:3304/attiead?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: sanghoon
    password: sanghoon1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    path: /api-docs
#    url: /docs/swagger.yaml
