spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student-service
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /api-docs
#    url: /docs/swagger.yaml
